# Generated by Django 3.0.3 on 2020-02-15 14:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_document'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Upload',
        ),
    ]
